name: Unit Tests

on:
  push:
    branches:
      - dev

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.x
    
    - name: Print PATH
      run: echo $PATH

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flask

    - name: Run unit tests
      run: |
        python -m unittest discover -s tests

  merge_to_main:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/dev' && success()
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Merge to main
        run: git merge --ff-only refs/heads/dev